### ISSUE TITLE
No available instance presets for Analog Way Pulse 2 

### ISSUE THREAD

**Issue by Singh-12** [bitfocus/companion-module-analogway-midra#10]
I've launched companion and added pulse 2 in the instances, but there are no available presets on the tab.  

Any help would be appreciated.

<img width="1466" alt="Screen Shot 2022-03-14 at 12 24 33 PM" src="https://user-images.githubusercontent.com/101583464/158216497-23d2cd39-911c-48c5-9b3c-a669a1562caa.png">
.

**Comment by Singh-12** [comment]
Never mind figured it out.  I have another question, so i have all my inputs on the analog way pulse 2 assigned to my stream deck 1 - 8.  I've changed all the background colors of the inputs to green.  What I would like to do is that when the input is live on screen 1 I would like that input button to turn red, similar to a production switcher.  Any ideas on how to do that?

**Comment by Pont3x** [comment]
How did you do it? Im still struggling with it.

**Comment by dnmeid** [comment]
The Midra module dosn't provide presets or feedbacks. You have to configure your buttons yourself by adding actions.
