### ISSUE TITLE
Analog way - Eikos 4K

### ISSUE THREAD

**Issue by djstenger** [bitfocus/companion-module-analogway-midra#12]
Hi 
Im missing the profile for Eikos 4K. Can you help create this?

**Comment by dnmeid** [comment]
There will be a new module for the Midra 4k series because the API is completely different from that of the old Midra devices.

**Comment by djstenger** [comment]
Cool. Any ETA for that? :)

**Comment by dnmeid** [comment]
To be safe I'd say within this year.

**Comment by djstenger** [comment]
Okay, then I will try using Universe Control instead

**Comment by dnmeid** [comment]
The AWJ module for Eikos 4K has been released 2022-11-21
