### ISSUE TITLE
Webserver: Analog Way Midra (QuickVu) Buttons don't show

### ISSUE THREAD

**Issue by willosof** [bitfocus/companion-module-analogway-midra#2]
_From @somerockenguy on September 18, 2018 13:36_

Adding buttons for the Analog Way Midra QuickVu do not show in the webserver.

**To Reproduce**
-Create an Analog Way Midra QuickVu instance
-Add some buttons
-Open Webserver

**Expected behavior**
Buttons should show

**Desktop (please complete the following information):**
 - Windows 10
 - chrome
 - 1.1.1.669

_Copied from original issue: bitfocus/companion#238_

**Comment by dnmeid** [comment]
What do you mean with webserver? The admin GUI of Companion, the Web Buttons, the Elgato Emulator or something else?
Is this problem only affecting buttons of the Midra module and other modules are working fine?
As far as I can see it there is a problem with the Web Buttons, but it is also affecting other modules (most likely all modules).

**Comment by somerockenguy** [comment]
Works now on the most current build. The error showed Web Buttons for all modules (playback pro, 2x irisdown remote show control and irisdown countdown timer) but any space where an Analog Way Midra button was placed would appear black/empty.

Still have the issue where clicking the buttons does not actually trigger anything and that "\n" is displayed as text, not a new line but those are different unrelated bugs.
