### ISSUE TITLE
Switch Layer Input In/Frame 10 switches to input 9

### ISSUE THREAD

**Issue by willosof** [bitfocus/companion-module-analogway-midra#3]
_From @SalkinDK on September 20, 2018 11:52_

**Describe the bug**
choosing a analogway-midra: Switch Layer Input action with the following settings, switches to input 9 (SDI 3) instead of input 10 (SDI 4)
Screen: S1
Preview/Program: Program
Layer: pip layer 1
Input: In/Frame 10

**To Reproduce**
Config the button with the settings above, and press test action.
It should work, but when you then go to instance and back to buttons, and press edit button, it have changed to In/Frame 9 instead.

**Expected behavior**
Should not change

**Screenshots**

**Desktop (please complete the following information):**
 - OS: osx
 - Browser chrome, and safari
 - Version companion-latest-osx.zip as of 2018-Sep-19 10:29

**Additional context**

_Copied from original issue: bitfocus/companion#247_

**Comment by dnmeid** [comment]
fixed in 917772bcb82a3bcb4d6a71e029b576addecfe40c
